cross_use:
  outputs:

    dev:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: trino
      password: [password]  # required if method is ldap or kerberos
      database: hive
      host: "{{ env_var('HIVE_HOST') }}"
      port: 8881
      schema: dev_cross_use_mart
      threads: 3

    prod:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: trino
      password: [password]  # required if method is ldap or kerberos
      database: hive
      host: "{{ env_var('HIVE_HOST') }}"
      port: 8881
      schema: cross_use_mart
      threads: 3

  target: dev

crypto_mart:
  outputs:

    dev:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: trino
      password: [password]  # required if method is ldap or kerberos
      database: hive
      host: "{{ env_var('HIVE_HOST') }}"
      port: 8881
      schema: dev_crypto_mart
      threads: 3

    prod:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: trino
      password: [password]  # required if method is ldap or kerberos
      database: hive
      host: "{{ env_var('HIVE_HOST') }}"
      port: 8881
      schema: crypto_mart
      threads: 3

  target: dev