
version: 2

sources:
  - name: cross_use__crypto_raw
    database: hive
    schema: crypto_raw
    tables:
      - name: candles_day
      - name: candles_minute
      - name: candles_realtime
      - name: market_trade
      - name: order_book
  - name: cross_use__forex_raw
    database: hive
    schema: forex_raw
    tables:
      - name: forex_rate_day
  - name: cross_use__gas_raw
    database: hive
    schema: gas_raw
    tables:
      - name: natural_gas_price_day
  - name: cross_use__gold_raw
    database: hive
    schema: gold_raw
    tables:
      - name: gold_price_day
  - name: cross_use__oil_raw
    database: hive
    schema: oil_raw
    tables:
      - name: crude_oil_price_day
  - name: cross_use__stock_raw
    database: hive
    schema: stock_raw
    tables:
      - name: stock_index_day
