
version: 2

sources:
  - name: crypto__crypto_raw
    database: hive
    schema: crypto_raw
    tables:
      - name: candles_day
      - name: candles_minute
      - name: candles_realtime
      - name: market_trade
      - name: order_book
  - name: crypto__util
    database: hive
    schema: util
    tables:
      - name: calendar